# Generated by Django 5.0.7 on 2024-07-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('author', models.TextField(max_length=150)),
                ('genre', models.TextField(max_length=80)),
            ],
        ),
    ]
