# Generated by Django 5.0.7 on 2024-07-26 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reader_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('staff_number', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
